FROM ubuntu
# copied from https://github.com/nacyot/docker-programming-languages/blob/master/fortran-gfortran-apt/Dockerfile

RUN apt-get update
RUN apt-get install -y gfortran

# Set default WORKDIR
WORKDIR /source
