#!/usr/bin/awk -f

BEGIN { checksum = 0 }
{
  for (i=2; i <= NF; i++) {
    for (j=1; j <i; j++) {
      if($i % $j == 0 || $j % $i == 0) {
        if ($i < $j) {
          checksum += $j / $i
        } else {
          checksum += $i / $j
        }
      }
    }
  }
}

END { print checksum }
